app_passcode = "1234"
sheet_name = "Health Tracker"

[gcp_service_account]
type = "service_account"
project_id = "project-test-471515"
private_key_id = "4bbcd74a768d3daac7a5e4500de526d68eee3441"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/mvv6LD3D5QCW\nhG8XO4JnVLmHmdftD53M8xw7USWs2Vc2aHdoIJRrQJ1JaI3MRKccJ3GjNNC07+6C\n...\n-----END PRIVATE KEY-----\n"
client_email = "health-tracker@project-test-471515.iam.gserviceaccount.com"
client_id = "112884768454480272930"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/health-tracker%40project-test-471515.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
