app_passcode = "1234"
sheet_name = "Health Tracker"

[gcp_service_account]
type = "service_account"
project_id = "project-test-471515"
private_key_id = "4bbcd74a768d3daac7a5e4500de526d68eee3441"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/mvv6LD3D5QCW
hG8XO4JnVLmHmdftD53M8xw7USWs2Vc2aHdoIJRrQJ1JaI3MRKccJ3GjNNC07+6C
MkVE1NHFy7DzTvZgDyK4W16jz1lkw9fIfobyEkJLKaA1sy0M1OBtMQ2fj3l9ZiQJ
XxmdbiwMdpM3jIs5xQHx+BO52bOl51nRmtv/Womgipg2Nu18yPo9ygNAJWjpMzL9
HGaFSYh3f6yMyGzcUdzKFQ/f81CJNKOqlizIGgXOOVem6xQoiwErsfZ7YsdBQQoh
8hc6BFrPvOlu3bdThD2wpOhpMI4elR/I2ZbyJUX3HYt4vTsMftQlL3NrKhJDZUd2
goEu9oxbAgMBAAECggEATr5NfvdunNLAxpr/or8grQGrS7ikfjb0RZXFzPTg9GPP
zTrqk78L7/X6jgArgj7WpKHrOEUM3sdaMGSjhhGmclDvVFbntvuRa82VG+IrnVdF
F480O0jYuNYPEvKjeYoE/6rwq9oFdk0jUzyjpMjxzl9uyh3229OEpKIszSzUgUHX
ifwuCqmB8/dyLvzyeBARyNo+SZ/+uhSccL8C6Pt81+Q+gw+KvGSBWywl4DEkXMTD
aq/5DeHVVizwIbJIJGqnbFpqAtzMVQbJZuiZV7mDkEk36mL4FpBFKmCbc9WIGE6t
rL4XdXkPRnqwdvbJxKrRSxS2PqD+tAnh1KnTk4itwQKBgQDz98XQuIbQz5EPuNJ+
8h92vaJ6eh4DDfTUOQjdP+kVMijPDtKLUyk8RWnnfMxARe/ToA+vvfasP4DzkUNJ
ugyHnavHvtNZ7SGw09xcyCcyqVm+dqHtYO+o1/djBLMESEmHriB5JUq+aI0+/OkK
KG+UpA4Z99J+ydcmoIHwAVaeQQKBgQDJDhtmJRpsSH1+LrDI9iq4SWkmY8FQoZuF
zcpv9tuaIMS20r+TpNDN4O66Qqop+qZ1m3drvzA2bp1pxGnHEdtHAMEmWvmwnYq3
fyO9qfLpKbYesDdRKfKe4wzAj6DkfdSmbdOcADQhONu/xs5JRq0/jYsqDlEr3wYa
4XV4YZv7mwKBgQDsjHlI/yH4pMlKLTIr1CedwhEgH/epjoasnwBxRd6Bprjaysxq
Op/oyIT+5opEZ4s57iBHjjD2ojwt7dMIUVSEyeQdMHFM6BealFE9xPP8sydI/U3U
FAFL/NrpL01EAbMJ01O5Iudt54HMaPyr1LkbrlXd5+Q4+wuZcFeMlj+eAQKBgQCm
ca5PFqJUSILTpnWmONzO6b9KD8VnKhLlZ6OSo2vTohMYQ0pkQUq3VeJsgmn7DM0n
icgIhCO2vEZG3Fqxed/tXPuJ9EDHbPT8yh1dk8dMLcLejwWMhMydqtvQwlbxMhaM
nVlUyXpekoKhtkTqtr8QYO53p5idWCnmsQWd3jjSxwKBgAJlA0fdW0fLaamCzSWq
FFAqIXEA8SO5M43dhyzQgchcozuLG7Lcb45MmEOU6qOYHwJymwsb+9MGz2uazRKh
SB/fhjPV08mfjzmXmSQ+CxMpH5cAQf4UQydEW/qm7RK6pUYEWovscLtIH30304nw
Iyrl+SqSVPiyeNs3u6uEj108
-----END PRIVATE KEY-----"""
client_email = "health-tracker@project-test-471515.iam.gserviceaccount.com"
client_id = "112884768454480272930"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/health-tracker%40project-test-471515.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
